/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class IMGLoad */

#ifndef _Included_IMGLoad
#define _Included_IMGLoad
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     IMGLoad
 * Method:    loadImage
 * Signature: (Ljava/lang/String;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_IMGLoad_loadImage
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
